apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumina-ingress
  namespace: lumina
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: lumina.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lumina-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lumina-frontend
                port:
                  number: 80
